admin_homepage_routes:
    resource: "@AdminBundle/Resources/config/routing/routing-admin-homepage.yml"
    
admin_pages_routes:
    resource: "@AdminBundle/Resources/config/routing/routing-admin-pages.yml"

admin_categories_routes:
    resource: "@AdminBundle/Resources/config/routing/routing-admin-categories.yml"